gallery/urls.py
from django.urls import path
from .views import AntennaListView, AntennaCreateView, CameraListView, AntennaUpdateView

urlpatterns = [
    path('antennas/list', AntennaListView.as_view(), name='list'),
    path('antennas/create', AntennaCreateView.as_view(), name='create_antenna'),
    path('antennas/<int:pk>/update', AntennaUpdateView.as_view(), name='update_antenna'),
    path('cameras/', CameraListView.as_view(), name='camera_list'),
]

test_gallery/urls.py
from django.contrib.staticfiles.urls import static
from django.contrib import admin
from django.urls import path, include

import gallery
from test_gallery import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models


def upload_to_gallery(instance, filename):
    return f"images/{instance.gallery.__class__.__name__}/{filename}"


class Gallery(models.Model):
    gallery_id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')

    def __str__(self):
        related_models = ['antenna', 'camera']  # Add more models here
        owner = next((getattr(self, model) for model in related_models if hasattr(self, model)), None)
        return f"{owner.__class__.__name__} {owner.id}" if owner else f"{self.__class__.__name__} {self.id}"

    @property
    def id(self):
        return self.gallery_id


class IdMixin(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')

    class Meta:
        abstract = True


class BasePartMixin(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        abstract = True


class Image(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ImageField(upload_to=upload_to_gallery)
    order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', '-created_at']
        unique_together = ('gallery', 'order')


class Antenna(BasePartMixin, IdMixin, Gallery):
    type = models.CharField(max_length=50, unique=True)


class Camera(BasePartMixin, Gallery, IdMixin):
    name = None
    type = models.CharField(max_length=50, unique=True)

gallery/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Antenna, Camera, Image


class AntennaForm(forms.ModelForm):
    class Meta:
        model = Antenna
        exclude = ()

class CameraForm(forms.ModelForm):
    class Meta:
        model = Camera
        exclude = ()


ImageInlineFormset = forms.inlineformset_factory(Antenna, Image, fields='__all__', min_num=1, extra=10, max_num=10)

gallery/views.py
from django.views.generic import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import AntennaForm, ImageInlineFormset
from .models import Antenna, Camera

class AntennaListView(ListView):
    model = Antenna
    template_name = 'antennas_list.html'
    context_object_name = 'antennas'

class CameraListView(ListView):
    model = Camera
    template_name = 'cameras_list.html'
    context_object_name = 'cameras'


class AntennaCreateView(CreateView):
    form_class = AntennaForm
    success_url = 'list'
    template_name = 'gallery/antenna_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['images'] = ImageInlineFormset(self.request.POST, self.request.FILES)
        else:
            context['images'] = ImageInlineFormset()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        images = context['images']
        if images.is_valid():
            self.object = form.save()
            images.instance = self.object.gallery_ptr
            images.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class AntennaUpdateView(UpdateView):
    model = Antenna
    form_class = AntennaForm
    success_url = 'update_antenna'
    template_name = 'gallery/antenna_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['images'] = ImageInlineFormset(self.request.POST, self.request.FILES)
        else:
            context['images'] = ImageInlineFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        images = context['images']
        if images.is_valid():
            self.object = form.save()
            images.instance = self.object.gallery_ptr
            images.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

templates/antennas_list.html
<!-- antennas_list.html -->
{% extends "base.html" %}

{% block title %}All Antennas{% endblock %}

{% block content %}
<h1>All Antennas</h1>

{% for antenna in antennas %}
  <div class="antenna">
    <h2>{{ antenna.name }} ({{ antenna.type }})</h2>
    
{#    {% if antenna.gallery_set.all %}#}
      <h3>Gallery:</h3>
      <ul>
      {% for image in antenna.gallery_images.all %}
        <li><img src="{{ image.image.url }}" alt="Antenna Image"></li>
      {% endfor %}
      </ul>
{#    {% endif %}#}
  </div>
{% endfor %}
</div>
</body>
</html>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

    {% block content %}
    {% endblock %}

</body>
</html>

templates/cameras_list.html
<!-- cameras_list.html -->
{% extends "base.html" %}

{% block title %}All Cameras{% endblock %}

{% block content %}
<h1>All Cameras</h1>

{% for camera in cameras %}
  <div class="camera">
    <h2>({{ camera.type }})</h2>
    
{#    {% if camera.gallery_set.all %}#}
      <h3>Gallery:</h3>
      <ul>
          {% for image in camera.gallery_images.all %}
              <li><img src="{{ image.image.url }}" alt="Camera Image"></li>
      {% endfor %}
      </ul>
{#    {% endif %}#}
  </div>
{% endfor %}
</body>
</html>


{% endblock %}

templates/gallery/antenna_form.html
{% extends "base.html" %}

{% block title %}Create Antenna{% endblock %}

{% block content %}
<h1>Create Antenna</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {{ form.as_p }}
    
    <h2>Gallery Images:</h2>
    {{ images.management_form }}
    {% for image_form in images %}
        <p>{{ image_form.image.label_tag }} {{ image_form.image }} {{ image_form.order }}</p>
    {% endfor %}
    
    <button type="submit">Create Antenna</button>
</form>

{% endblock %}